### ISSUE TITLE
JSON Format

### ISSUE THREAD

**Issue by eylmz** [yusufcakal/CuYemek#2]
JSON'u encode ederken ikinci parametre olarak 256 verde düzgün gözüksün

**Comment by yusufcakal** [comment]
https://gist.github.com/yusufcakal/32e43bfe55cc2691bd12a5ee222d01b6 nasıl anlamadım ?

**Comment by eylmz** [comment]
Sivas'ıncı satırı şununla değiştir : echo json_encode(array('içerik' => $contentNames),256);

**Comment by yusufcakal** [comment]
Değiştirmiştim de söylediğinde bir fark göremedim.
